---
- name: "Assuing Custom Share Exists"
  ansible.builtin.file:
    path: "{{ __samba_usershare_dropin }}"
    mode: 0644
    owner: root
    group: root
    state: touch

- name: "Creating the directory for the share {{ item.name }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0777', true) }}"
    owner: "{{ item.owner | default('root', true) }}"
    group: "{{ item.group | default('root', true) }}"
