---
# tasks file for samba
- name: "Including Samba Server Setup for a Host Level"
  ansible.builtin.include_tasks:
    file: "host_setup.yml"
    apply:
      tags:
        - host
  tags:
    - host
    - never
  when: samba_mode == "host"

- name: "Including Samba Server Setup as Quadlet Container"
  ansible.builtin.include_tasks:
    file: "quadlet_setup.yml"
    apply:
      tags:
        - quadlet
        - never
  tags:
    - quadlet
    - never
  when: samba_mode == "quadlet"

- name: "Including SELinux Setup"
  ansible.builtin.include_tasks:
    file: "selinux_setup.yml"
  when: samba_selinux|bool
