---
- name: Converge on Host
  hosts: cs8
  gather_facts: false
  roles:
    - role: samba
      samba_mode: "host"
      samba_protocol: "NT1"

- name: Converge on Quadlet
  hosts: pinp
  gather_facts: false
  roles:
    - role: samba
      samba_mode: "quadlet"
      samba_protocol: "CORE"
