# Samba Server Container File
FROM        quay.io/centos/centos:stream8
RUN         dnf -y install epel-release
RUN         dnf -y install \
            supervisor \
            {% for pkg in samba_packages %}{{ pkg }} {% endfor %}

EXPOSE      137/udp 137/tcp 138/udp 138/tcp 139/udp 139/tcp 445/udp 445/tcp
COPY        smb-nmb-supervisor.ini /etc/supervisord.d/smb-nmb.ini
ENTRYPOINT  ["/usr/bin/supervisord"]
